### ISSUE TITLE
cpuminer-opt cannot mine in public-pool.io

### ISSUE THREAD

**Issue by PSLLSP** [benjamin-wilson/public-pool#13]
Some issue with startum method [mining.authorize](https://en.bitcoin.it/wiki/Stratum_mining_protocol#mining.authorize). [`cpuminer-opt`](https://github.com/rplant8/cpuminer-opt-rplant) sends more parameters and is rejected by [public-pool.io](https://web.public-pool.io/). I am not sure why it sends more parameters, maybe that is for newer version of stratum protocol.

[cpuminer-opt](https://github.com/rplant8/cpuminer-opt-rplant) can mine in [ckpool.org](https://solo.ckpool.org), it is not rejected...

accepted by all pools:

```
{"id": 2, "method": "mining.authorize", "params": ["1Bkg23fU9EnazGw2yyYVwQKHmjq1MRsEx4.TEST", "x"]}
```

rejected by public-pool.io:

```
{"id": 2, "method": "mining.authorize", "params": ["1Bkg23fU9EnazGw2yyYVwQKHmjq1MRsEx4.TEST", "x", ["s2", "b"]]}
```

Details are described in this [issue](https://github.com/rplant8/cpuminer-opt-rplant/issues/55)

**Comment by benjamin-wilson** [comment]
This seems to be an issue with cpuminer-opt and not the pool
