### ISSUE TITLE
Public Pool crashes when loaded with too much hashpower

### ISSUE THREAD

**Issue by sethforprivacy** [benjamin-wilson/public-pool#16]
Unfortunately the only log line I got was this repeating endlessly, as everything before it was lost:

`Error: Cannot write to closed or ended socket. 1ad1fe36 {"id":93,"error":null,"result":true}`

It eventually ended with more standard logs:

```
public-pool  | Error: Cannot write to closed or ended socket. c5b287f0 {"id":86,"error":null,"result":true}
public-pool  | 
public-pool  | Error: Cannot write to closed or ended socket. 2f5c627c {"id":339,"error":null,"result":true}
public-pool  | 
public-pool  | Killing dead clients
public-pool  | Killing dead clients
public-pool  | Client b5b59ed0 disconnected, hadError?:true
```

Cause:

https://x.com/checksum0/status/1738323047264743758?s=20

![image](https://github.com/benjamin-wilson/public-pool/assets/40500387/6e01e3c4-2a2d-49f3-b641-8d1844ed32b2)

**Comment by sethforprivacy** [comment]
One additional note, he noted that the diff never adjusted >2048:

https://x.com/checksum0/status/1738334712752439719?s=20

**Comment by benjamin-wilson** [comment]
Significant improvements have been made but server resources do need to be sized according to the number of clients. There is also the postgresql branch which is recommended for hosting more than a few thousand clients.
