### ISSUE TITLE
Feature request: Bitcoin Knots instead of Bitcoin Core in order to protect Bitcoin network against spam

### ISSUE THREAD

**Issue by GregTonoski** [benjamin-wilson/public-pool#17]
Can I ask you to replace Bitcoin Core with Bitcoin Knots so that mined blocks would not include spam, please?

Bitcoin Knots: https://github.com/bitcoinknots/bitcoin

**Comment by benjamin-wilson** [comment]
The pools and pleases RPC to connect to whichever you prefer. It is agnostic, and I don't include either.
