### ISSUE TITLE
Pool stopped working when SSL certificate went live

### ISSUE THREAD

**Issue by Magius79** [benjamin-wilson/public-pool#18]
I had my pool up and running and my miner was connected fine to it. Around the time my SSL certificate went live it stopped working. The following error now appears in the log:

Error getmininginfo Loading block index…

The website is still accessible and shows the public pool page, but I can't connect my miner to it anymore. Any advice?

**Comment by benjamin-wilson** [comment]
Loading block index error when indicate that your Bitcoin node is busy. I don't think it's related to SSL

**Comment by Magius79** [comment]
I actually was able to get it working by shutting down docker compose, disabling the ufw firewall, restarting the firewall, restarting bitcoind by itself, then restarting the rest of public-pool. Not sure which of those steps fixed it, but in the end it has started working again.
