### ISSUE TITLE
Enhancement: Miningpoolstream API endpoints

### ISSUE THREAD

**Issue by WantClue** [benjamin-wilson/public-pool#21]
In order to show all our stats from public pool to the Miningpoolstream website we need the follwing Data available for them to fetch:
pool hashrate , miners , fee , height , blocks_found*

**Comment by github-block** [comment]
You can check your stats using the following API 
https://public-pool.io:40557/api/client/yourBTCadress

**Comment by WantClue** [comment]
> You can check your stats using the following API https://public-pool.io:40557/api/client/yourBTCadress

You might misunderstood this issue. 
This is an enhancement request for future API endpoints and not an issue in terms of "having an issue"

**Comment by WantClue** [comment]
done by #23
