### ISSUE TITLE
Question: What could be wrong with this "mining.authorize" message?

### ISSUE THREAD

**Issue by KaSt** [benjamin-wilson/public-pool#28]
Good day,
as someone reported some time ago, some miners, old miners I gather, aren't compatible with this wonderful pool.
In this case I'm talking about bfgminer 5.5.0 which I run on a Onion Omega 2+ (openwrt) with some old USB miners.

The "mining.authorize" message doesn't pass validation. I never used nextjs and not a Stratum expert but the only thing I noticed is that the message id in this case is not numeric, the "subscribe" one is.

What could be wrong with this message?
{"id": "auth", "method": "mining.authorize", "params": ["my Bitcoin address was removed", "x"]} 

I tried to check the pool code for the validation performed but so far could only find the validation of the params section, based on the "mining.authorize" method.

In case somebody has an idea.

Thanks for the great work.

**Comment by ofawx** [comment]
Currently the `id` must be numeric:
https://github.com/benjamin-wilson/public-pool/blob/2e296c00d57a30e2e3b422f5b6b111d746261678/src/models/stratum-messages/StratumBaseMessage.ts#L6-L7

I can't see any strict requirement for this elsewhere in the codebase, and stratum mining lacks formal spec, so expect this could be removed for better compatibility.

**Comment by benjamin-wilson** [comment]
Removed the requirement 
https://github.com/benjamin-wilson/public-pool/commit/f08103bd8c725c796d9f31d2d0d18b2fcf08d5de
