### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by Retropex** [benjamin-wilson/public-pool#3]
Small error, I'm not sure if the error is related to public pool or not.

```
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

**Comment by benjamin-wilson** [comment]
It's a network error but this should handle it more gracefully. https://github.com/benjamin-wilson/public-pool/commit/2cc60777d5e463f6cc41035820c8c09fcdf89ac6
