### ISSUE TITLE
Add TLS 1.3 for public-pool

### ISSUE THREAD

**Issue by SiriusLightning21** [benjamin-wilson/public-pool#30]
Ist it possible to add TLS 1.3? I opened an issue at cromites repo and they that TLS 1.3 is not active.

https://github.com/uazo/cromite/issues/795

**Comment by sethforprivacy** [comment]
You shouldn't be exposing public-pool directly, and instead should normally be running it behind a reverse proxy of some sort that handles SSL/termination. Your SSL settings should be handled upstream by the reverse proxy, while public-pool-ui handles just the simple serving of the web page.

Also note that the proper repo for questions about the UI is here:

https://github.com/benjamin-wilson/public-pool-ui
