### ISSUE TITLE
got this error Module '"discord.js"' declares 'GatewayIntentBits' locally...

### ISSUE THREAD

**Issue by recom3** [benjamin-wilson/public-pool#34]
src/services/discord.service.ts:4:38 - error TS2460: Module '"discord.js"' declares 'GatewayIntentBits' locally, but it is exported as 'Snowflake'.

My node version is
v18.16.0

In fact got 2 errors in discord.js:

src/services/discord.service.ts:4:38 - error TS2460: Module '"discord.js"' declares 'GatewayIntentBits' locally, but it is exported as 'Snowflake'.

4 import { Client, Collection, Events, GatewayIntentBits, REST, Routes, SlashCommandBuilder, TextChannel } from 'discord.js';
                                       ~~~~~~~~~~~~~~~~~

  node_modules/discord.js/typings/index.d.ts:105:3
    105   GatewayIntentBits,
          ~~~~~~~~~~~~~~~~~
    'GatewayIntentBits' is declared here.
src/services/discord.service.ts:4:63 - error TS2305: Module '"discord.js"' has no exported member 'Routes'.

4 import { Client, Collection, Events, GatewayIntentBits, REST, Routes, SlashCommandBuilder, TextChannel } from 'discord.js';
                                                                ~~~~~~

Found 2 error(s).

Thx very much

**Comment by benjamin-wilson** [comment]
unable to reproduce
