### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by marssystems** [benjamin-wilson/public-pool#4]
H:\public-pool>npm run test

> public-pool@0.0.1 test
> jest

 FAIL  src/models/StratumV1Client.spec.ts
  ● Test suite failed to run

    src/models/StratumV1Client.spec.ts:129:13 - error TS2345: Argument of type 'PromiseSocket<any>' is not assignable to parameter of type 'Socket'.
      Type 'PromiseSocket<any>' is missing the following properties from type 'Socket': pause, resetAndDestroy, resume, setNoDelay, and 56 more.

    129             promiseSocket,
                    ~~~~~~~~~~~~~

 PASS  src/models/stratum-messages/MiningSubmitMessage.spec.ts (5.848 s)
 PASS  src/controllers/address/address.controller.spec.ts (5.933 s)
 PASS  src/controllers/client/client.controller.spec.ts (7.976 s)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        8.526 s
Ran all test suites.

H:\public-pool>

**Comment by benjamin-wilson** [comment]
Fixed https://github.com/benjamin-wilson/public-pool/commit/d8059db561bc4256f6d40fca619c8c6c4ee950cd

**Comment by marssystems** [comment]
OK - both tests pass now - thanks!
