### ISSUE TITLE
Mine on testnet4

### ISSUE THREAD

**Issue by 1ma** [benjamin-wilson/public-pool#41]
I tried to set up a testnet4 pool, but even though public-pool can connect to Bitcoin Core and the miner can connect to public-pool it doesn't mine, and something seems broken in the logs.

![GNzvsqCWMAEcMb-](https://github.com/benjamin-wilson/public-pool/assets/1456708/52e2f160-2f40-4836-a871-8fe85e35fe2e)

**Comment by benjamin-wilson** [comment]
Doesn't look like the .env is configured correctly
