### ISSUE TITLE
Unhandled error - getblocktemplate: Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by schneimi** [benjamin-wilson/public-pool#47]
When this error happens, my Bitaxe has restarted as well as the Docker container of the pool server. Cannot tell what is first or what causes this. It happened twice within 2-3 weeks. Maybe this should be catched.

```
Error getblocktemplate: Error: ESOCKETTIMEDOUT
/public-pool/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
            throw err;
            ^

Error: Error getblocktemplate
    at BitcoinRpcService.getBlockTemplate (/public-pool/dist/services/bitcoin-rpc.service.js:114:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.1
```

**Comment by benjamin-wilson** [comment]
This is caused by Bitcoin core rpc not responding in a timely manner and indicates the hardware is under powered
