### ISSUE TITLE
Online devices on main page not showed correctly

### ISSUE THREAD

**Issue by lcharles123** [benjamin-wilson/public-pool#48]
This is the page, it shows Devices like "cgminer" with 57TH but best diff at 175M, its possible but improbable.
I used cgminer with 666 GH for 3 weeks and found a hash with more than 3G diff

![image](https://github.com/benjamin-wilson/public-pool/assets/8680067/ff20aec0-f604-47ed-ad64-674f018cd7d4)

**Comment by benjamin-wilson** [comment]
The statistics are correct
