### ISSUE TITLE
Wrong difficulty on testnet4

### ISSUE THREAD

**Issue by Retropex** [benjamin-wilson/public-pool#51]
<img width="261" alt="image" src="https://github.com/user-attachments/assets/2c488a84-72e9-4ba1-97c4-fe88f8b9b317">

**Comment by benjamin-wilson** [comment]
The difficulty comes from RPC, if there is no block in 20minutes, difficulty will drop to 1, so this might have been correct.

**Comment by remcoros** [comment]
bitcoin core rpc returns the difficulty based on the hash of last block (not the actual current difficulty). Since a lot of blocks are mined in the future (allowing a difficulty of 1), you often see the difficulty as 1, even if a block has 'just been mined'.
