### ISSUE TITLE
low block model refresh rate

### ISSUE THREAD

**Issue by Retropex** [benjamin-wilson/public-pool#55]
On commit deed775d5561a2c9a21dfe595260225ec676344f (I'm using this one because of the issue #54) the block template seems to only be actualized when a new block is mined

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6d18929c-d63a-4816-9d3e-1937aea4a3ce">

**Comment by benjamin-wilson** [comment]
This was fixed in c654a706aea94fb3face5c589b460e6b94e05778
