### ISSUE TITLE
Stratum Client Auth failed

### ISSUE THREAD

**Issue by tomasvanagas** [benjamin-wilson/public-pool#56]
Hello,

When trying to point miner to this stratum pool authorization fails. I dont want to run multi-user setup - mining only by myself.

Is there a default login?

```
public-pool  | Client 662144e7 disconnected, hadError?:false
public-pool  | block height change
public-pool  | Killing dead clients
public-pool  | New client ID: : b76bba4b, ::ffff:<REDACTED_IP>:37586
public-pool  | Authorization validation error
public-pool  | {"id":34406,"result":null,"error":[20,"Authorization validation error",", 1, "]}

```

**Comment by benjamin-wilson** [comment]
This is a result of a malformatted authorization message "validation error", not authentication. There is no login.
