### ISSUE TITLE
Add Block Notify to prevent stale mining

### ISSUE THREAD

**Issue by copy2018** [benjamin-wilson/public-pool#78]
To prevent the mining of stale work for many seconds after a new block has been found we should try to add the bitcoin knots ''Block Notify'' support so a command can be executed to have the node directly notify that a new block has been found to public pool.

A similar thing has been implemented in Datum.

This would help increase the time we are hashing up to date work, if that's what you call it.

**Comment by benjamin-wilson** [comment]
Public pool subscribes to ZMQ 'rawblock' 
`rawblock: Notifies when the chain tip is updated`
At which time a new block template is generated and pushed out with clearjobs=true so no time is wasted mining stale data other than the network latency.
